export const GET_USERS_REQUEST = 'GET_USERS_REQUEST';
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
export const GET_USERS_FAILURE = 'GET_USERS_FAILURE';

export const LOGGED_IN = 'LOGGED_IN';

export const STUDENT_ID_REQUEST = 'STUDENT_ID_REQUEST';
export const STUDENT_ID_SUCCESS  = 'STUDENT_ID_SUCCESS ';
export const STUDENT_ID_FAILURE = 'STUDENT_ID_FAILURE';

export const DIS_ITEM_ID = 'DIS_ITEM_ID';

export const GET_DISCIPLINES_REQUEST = 'GET_DISCIPLINES_REQUEST';
export const GET_DISCIPLINES_SUCCESS = 'GET_DISCIPLINES_SUCCESS';
export const GET_DISCIPLINES_FAILURE = 'GET_DISCIPLINES_FAILURE';

export const TEACHER_ID_REQUEST = 'TEACHER_ID_REQUEST';
export const TEACHER_ID_SUCCESS  = 'TEACHER_ID_SUCCESS ';
export const TEACHER_ID_FAILURE = 'TEACHER_ID_FAILURE';

export const TASK_ITEM_ID = 'TASK_ITEM_ID';

export const ADD_TASK_REQUEST = 'ADD_TASK_REQUEST';
export const ADD_TASK_SUCCESS = 'ADD_TASK_SUCCESS';
export const ADD_TASK_FAILURE = 'ADD_TASK_FAILURE';